version: "3.7"

services:
  rp_bag_db:
    image: postgres
    container_name: rp_bag_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rp_bag
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rp_bag
    ports:
      - 3001:3001
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - rp_bag_db
    depends_on:
      - rp_bag_db

volumes:
  pgdata:
    driver: local
