version: "3"
services:
  web:
    build:
      dockerfile: ./docker.Dockerfile
      context: .
    image: filipenadai/rp-bag
    container_name: rp-bag
    ports:
      - "3000:3000"
    command: npm run dev
    env_file:
      - ./api/.env
    networks:
      - rp-bag-network
    depends_on:
      - pg
      - pg-test
    links:
      - pg
      - pg-test
    volumes:
      - ./api:/var/www
      - /var/www/node_modules
    restart: always

  pg:
    image: postgres
    container_name: rp-bag-pg
    volumes:
      - ./pg/:/var/lib/pg
    ports:
      - 5432:5432
    networks:
      - rp-bag-network
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rp-bag
    restart: always

  pg-test:
    image: postgres
    container_name: rp-bag-pg-test
    volumes:
      - /var/lib/pg
    ports:
      - 5433:5432
    networks:
      - rp-bag-network
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rp-bag-test
    restart: always

networks:
  rp-bag-network:
    driver: bridge